#!/bin/bash

# Various computers on my local network
MACBOOK_HOST="Huckleberry"
MACBOOK_USER="Diesel"
MACBOOK="$MACBOOK_USER:$MACBOOK_HOST"

NETBOOK_HOST="magilla"
NETBOOK_USER="bryan"
NETBOOK="$NETBOOK_USER:$NETBOOK_HOST"

# Template for new hosts.
# _HOST=""
# _USER=""
# ="$_USER:$_HOST"
